insert into Clients (FirstName, LastName, RegistrationDate) values
	("Dianne","Haddix",CURDATE()) ,
	("Jeanice","Mohler",CURDATE()) ,
	("Eleonor","Sylvester",CURDATE()) ,
	("Autumn","Balliet",CURDATE()) ,
	("Willia","Zamor",CURDATE()) ,
	("Marine","Lucht",CURDATE()) ,
	("Akilah","Hoyos",CURDATE()) ,
	("Terrell","Colbert",CURDATE()) ,
	("Parthenia","Kohr",CURDATE()) ,
	("Marla","Kroenke",CURDATE()) ,
	("Ami","Esqueda",CURDATE()) ,
	("Alethea","Fullen",CURDATE()) ,
	("Willena","Rickards",CURDATE()) ,
	("Brittanie","Malik",CURDATE()) ,
	("Carmelia","Torrez",CURDATE()) ,
	("Loriann","Bruss",CURDATE()) ,
	("Rivka","Butt",CURDATE()) ,
	("Emmett","Oleson",CURDATE()) ,
	("Oneida","Wanamaker",CURDATE()) ,
	("Kristle","Klatt",CURDATE()) ,
	("Rea","Erby",CURDATE()) ,
	("Sidney","Minchew",CURDATE()) ,
	("Iesha","Matherly",CURDATE()) ,
	("Lizette","Segui",CURDATE()) ,
	("Julene","Reisner",CURDATE()) ,
	("Lilly","Winchell",CURDATE()) ,
	("Rodolfo","Bridger",CURDATE()) ,
	("Kristine","Seigel",CURDATE()) ,
	("Kalyn","Arbeiter",CURDATE()) ,
	("Giovanni","Sherry",CURDATE()) ,
	("Brittany","Speaks",CURDATE()) ,
	("Rayna","Tartaglia",CURDATE()) ,
	("Claris","Conely",CURDATE()) ,
	("Emely","Laber",CURDATE()) ,
	("Lester","Veneziano",CURDATE()) ,
	("Roland","Amburn",CURDATE()) ,
	("Marlin","Trump",CURDATE()) ,
	("Rozella","Collette",CURDATE()) ,
	("Rey","Gwozdz",CURDATE()) ,
	("Jaye","Boose",CURDATE()) ,
	("Taryn","Brazeau",CURDATE()) ,
	("Bianca","Maye",CURDATE()) ,
	("Jeffry","Rake",CURDATE()) ,
	("Christiana","Ferrigno",CURDATE()) ,
	("Ada","Bitterman",CURDATE()) ,
	("Hye","Broyles",CURDATE()) ,
	("Sebastian","Blais",CURDATE()) ,
	("Kiana","Scoles",CURDATE()) ,
	("Essie","Galbraith",CURDATE()) ,
	("Ashanti","Dear",CURDATE()) ;
insert into Species (Name, ObligatoryProcedures,Description, LegalIssues) values ("cat","","","");
insert into Animals (Clients_ClientID, Name, RegistrationDate,Birth, Gender, Height, Weight , Species_Name) values
	(1,"Isabelle",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(1,"Westie",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(2,"Kona",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(2,"Harrison",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(3,"Clyde",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(3,"Bruno",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(4,"Holly",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(4,"Squirt",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(5,"Mack",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(5,"Bernie",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(6,"Pokey",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(6,"Millie",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(7,"Casper",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(7,"Queenie",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(8,"Emmy",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(8,"Sophia",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(9,"Fuzzy",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(9,"Lightning",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(10,"Dunn",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(10,"Ziggy",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(11,"Lulu",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(11,"Mia",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(12,"Fuzzy",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(12,"Stormy",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(13,"Rollie",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(13,"Louie",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(14,"Rexy",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(14,"Gromit",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(15,"Lou",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(15,"Tango",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(16,"Bobo",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(16,"Bella",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(17,"Skipper",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(17,"Ziggy",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(18,"Spotty",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(18,"Pretty",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(19,"Sammy",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(19,"Julius",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(20,"Wolfgang",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(20,"Archie",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(21,"Guinness",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(21,"Buddy",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(22,"Aj",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(22,"Kallie",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(23,"China",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(23,"Carley",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(24,"Jetta",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(24,"Tobie",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(25,"Tommy-boy",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(25,"Plato",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(26,"Sheba",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(26,"Budda",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(27,"Rover",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(27,"Silver",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(28,"Buck",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(28,"Dude",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(29,"Spotty",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(29,"Tripod",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(30,"Macho",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(30,"Wesley",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(31,"Pugsley",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(31,"Tucker",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(32,"Pearl",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(32,"Lulu",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(33,"Jolly",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(33,"Salem",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(34,"Schotzie",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(34,"Giant",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(35,"Franky",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(35,"Dozer",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(36,"Butterball",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(36,"Rocky",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(37,"Kibbles",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(37,"Mookie",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(38,"Georgie",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(38,"Snuffles",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(39,"Cosmo",CURDATE(),CURDATE()-100,"male", 0, 0, "cat") ,
	(39,"Brutus",CURDATE(),CURDATE()-100,"male", 0, 0, "cat");
