# Generated by Django 2.1.4 on 2019-01-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animalid', models.AutoField(db_column='AnimalID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('registrationdate', models.DateField(db_column='RegistrationDate')),
                ('birth', models.DateField(db_column='Birth')),
                ('gender', models.CharField(db_column='Gender', max_length=6)),
                ('height', models.FloatField(db_column='Height')),
                ('weight', models.FloatField(db_column='Weight')),
                ('otherdetails', models.CharField(blank=True, db_column='OtherDetails', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Animals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentid', models.AutoField(db_column='AppointmentID', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('status', models.CharField(db_column='Status', max_length=20)),
                ('details', models.CharField(db_column='Details', max_length=20)),
            ],
            options={
                'db_table': 'Appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientid', models.AutoField(db_column='ClientID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=20)),
                ('lastname', models.CharField(db_column='LastName', max_length=20)),
                ('registrationdate', models.DateField(db_column='RegistrationDate')),
            ],
            options={
                'db_table': 'Clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosisid', models.AutoField(db_column='DiagnosisID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='Code', max_length=20)),
                ('description', models.CharField(db_column='Description', max_length=200)),
                ('status', models.CharField(db_column='Status', max_length=20)),
                ('treatment', models.CharField(db_column='Treatment', max_length=200)),
            ],
            options={
                'db_table': 'Diagnoses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnosisMedicalprocedure',
            fields=[
                ('diagnosis_medicalprocedureid', models.AutoField(db_column='Diagnoses_MedicalProceduresID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Diagnoses_MedicalProcedures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnosisMedication',
            fields=[
                ('diagnosis_medicationid', models.AutoField(db_column='Diagnoses_MedicationsID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Diagnoses_Medications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicalprocedure',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=20, primary_key=True, serialize=False)),
                ('cost', models.FloatField(db_column='Cost')),
                ('otherdetails', models.CharField(blank=True, db_column='OtherDetails', max_length=200, null=True)),
            ],
            options={
                'db_table': 'MedicalProcedures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=20, primary_key=True, serialize=False)),
                ('cost', models.FloatField(db_column='Cost')),
                ('otherdetails', models.CharField(blank=True, db_column='OtherDetails', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Medications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('noteid', models.AutoField(db_column='NoteID', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='NoteDate')),
                ('content', models.IntegerField(db_column='Content')),
            ],
            options={
                'db_table': 'Notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=20, primary_key=True, serialize=False)),
                ('obligatoryprocedures', models.CharField(db_column='ObligatoryProcedures', max_length=20)),
                ('description', models.CharField(db_column='Description', max_length=200)),
                ('legalissues', models.CharField(db_column='LegalIssues', max_length=200)),
            ],
            options={
                'db_table': 'Species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('vetid', models.AutoField(db_column='VetID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=20)),
                ('lastname', models.CharField(db_column='LastName', max_length=20)),
                ('qualifications', models.CharField(db_column='Qualifications', max_length=20)),
                ('birth', models.DateField(db_column='Birth')),
            ],
            options={
                'db_table': 'Vets',
                'managed': False,
            },
        ),
    ]
